
[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.16.0"  # Replace with your actual Node version if different

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
